apiVersion: v1
kind: Pod
metadata:
  name: qos-guaranteed
  #namespace: qos-example
  labels:
   app: utrains
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          memory: "250Mi"
          cpu: "400m"
        requests:
          memory: "250Mi"
          cpu: "400m"