apiVersion: v1
kind: Secret
metadata:
  name: mysecret
<<<<<<< HEAD
type: Opaque
data:
  db_username: bWFzdGVyCg==
  db_password: cGFwaWxvdG9uQGdtYWlsLmNvbQo=
=======
  namespace: default
type: Opaque
data:
  mysql_pass: cGFwaWxvdG9u
>>>>>>> 7fb81b8ca00a243750d0fae93ae8c9ba7e4b8a6b
